db.Employee.insert
	(
		{
			"EName" : "Suman",
			"department":"development_staff",
			"designation":"Developer",
			"salary":"6000",
			"dateofjoining":"01/12/1998",
			"city":"Delhi",
		},
		{
			"Ename":"Martin",
			"department":"clerical staff", 
			"designation": "clerk", 
			"salary":"10000", 
			"dateofjoining":"01/02/1999", 
			"city":"singapore",
		},
		{
			"Ename":"Sagar",
			"department":"developement staff", 
			"designation": "devloper", 
			"salary":"15000", 
			"dateofjoining":"01/03/2000", 
			"city":"Banglore",
		},
		{
			"Ename":"Manish",
			"department":"clerical staff", 
			"designation": "clerk", 
			"salary":"7000", 
			"dateofjoining":"01/02/1999", 
			"city":"singapore",
		},
		{
			"Ename":"Brock",
			"department":"clerical staff", 
			"designation": "clerk", 
			"salary":"8000", 
			"dateofjoining":"01/02/1999", 
			"city":"singapore",
		},
		{
			"Ename":"Dhoni",
			"department":"clerical staff", 
			"designation": "clerk", 
			"salary":"10000", 
			"dateofjoining":"01/02/1999", 
			"city":"singapore",
		},
		{
			"Ename":"Kohli",
			"department":"clerical staff", 
			"designation": "clerk", 
			"salary":"20000", 
			"dateofjoining":"01/02/1999", 
			"city":"singapore",
		},
		{
			"Ename":"Martin",
			"department":"clerical staff", 
			"designation": "clerk", 
			"salary":"35000", 
			"dateofjoining":"01/02/1999", 
			"city":"singapore",
		},
		{
			"Ename":"Martha",
			"department":"clerical staff", 
			"designation": "clerk", 
			"salary":"50000", 
			"dateofjoining":"01/02/1999", 
			"city":"singapore",
		},
		{
			"Ename":"Murgan",
			"department":"clerical staff", 
			"designation": "clerk", 
			"salary":"10000", 
			"dateofjoining":"01/02/1999", 
			"city":"singapore",
		}
	);